Repository PayButton/paybutton-server, pull requests merged in 2025-08, with the labels that each got.

#1023 feat: org address
  components/Organization/UpdateOrganization.tsx
  components/Organization/ViewOrganization.tsx
  constants/index.ts
  prisma/migrations/20250711220324_/migration.sql
  prisma/schema.prisma
  services/organizationService.ts
  utils/validators.ts
Labels: enhancement (UI/UX/feature)

#1033 New ChronikService tests
  tests/unittests/chronikService.test.ts
Labels: enhancement (development)

#1028 Fix: Added invalid JSON check on payment triggers
  .github/coding-instructions.md
  services/triggerService.ts
  tests/unittests/triggerService.test.ts
Labels: bug, enhancement (behind the scenes)
